export const CATEGORIES = [
  { id: 'Fiction', name: 'Fiction' },
  { id: 'Nonfiction', name: 'Nonfiction' },
  { id: 'Antiques & Collectibles', name: 'Antiques & Collectibles' },
  { id: 'Literary Collections', name: 'Literary Collections' },
  { id: 'Architecture', name: 'Architecture' },
  { id: 'Literary Criticism', name: 'Literary Criticism' },
  { id: 'Art', name: 'Art' },
  { id: 'Mathematics', name: 'Mathematics' },
  { id: 'Bibles', name: 'Bibles' },
  { id: 'Medical', name: 'Medical' },
  { id: 'Biography & Autobiography', name: 'Biography & Autobiography' },
  { id: 'Music', name: 'Music' },
  { id: 'Body, Mind & Spirit', name: 'Body, Mind & Spirit' },
  { id: 'Nature', name: 'Nature' },
  { id: 'Business & Economics', name: 'Business & Economics' },
  { id: 'Performing Arts', name: 'Performing Arts' },
  { id: 'Comics & Graphic Novels', name: 'Comics & Graphic Novels' },
  { id: 'Pets', name: 'Pets' },
  { id: 'Computers', name: 'Computers' },
  { id: 'Philosophy', name: 'Philosophy' },
  { id: 'Cooking', name: 'Cooking' },
  { id: 'Photography', name: 'Photography' },
  { id: 'Crafts & Hobbies', name: 'Crafts & Hobbies' },
  { id: 'Poetry', name: 'Poetry' },
  { id: 'Design', name: 'Design' },
  { id: 'Political Science', name: 'Political Science' },
  { id: 'Drama', name: 'Drama' },
  { id: 'Psychology', name: 'Psychology' },
  { id: 'Education', name: 'Education' },
  { id: 'Reference', name: 'Reference' },
  { id: 'Family & Relationships', name: 'Family & Relationships' },
  { id: 'Religion', name: 'Religion' },
  { id: 'Science', name: 'Science' },
  { id: 'Games & Activities', name: 'Games & Activities' },
  { id: 'Self-Help', name: 'Self-Help' },
  { id: 'Gardening', name: 'Gardening' },
  { id: 'Social Science', name: 'Social Science' },
  { id: 'Health & Fitness', name: 'Health & Fitness' },
  { id: 'Sports & Recreation', name: 'Sports & Recreation' },
  { id: 'History', name: 'History' },
  { id: 'Study Aids', name: 'Study Aids' },
  { id: 'House & Home', name: 'House & Home' },
  { id: 'Technology & Engineering', name: 'Technology & Engineering' },
  { id: 'Humor', name: 'Humor' },
  { id: 'Transportation', name: 'Transportation' },
  { id: 'Juvenile Fiction', name: 'Juvenile Fiction' },
  { id: 'Travel', name: 'Travel' },
  { id: 'Juvenile Nonfiction', name: 'Juvenile Nonfiction' },
  { id: 'True Crime', name: 'True Crime' },
  { id: 'Language Arts & Disciplines', name: 'Language Arts & Disciplines' },
  { id: 'Young Adult Fiction', name: 'Young Adult Fiction' },
  { id: 'Language Study', name: 'Language Study' },
  { id: 'Young Adult Nonfiction', name: 'Young Adult Nonfiction' },
  { id: 'Law', name: 'Law' },
] as const

export type CategoryId = typeof CATEGORIES[number]['id'] 