// Configuration for supported languages
export const LANGUAGES = [
  { code: 'af', name: 'Afrikaans' },
  { code: 'am', name: 'Amharic' },
  { code: 'ar', name: 'Arabic' },
  { code: 'az', name: 'Azerbaijani' },
  { code: 'be', name: 'Belarusian' },
  { code: 'bg', name: 'Bulgarian' },
  { code: 'bn', name: 'Bengali' },
  { code: 'bs', name: 'Bosnian' },
  { code: 'ca', name: 'Catalan' },
  { code: 'ceb', name: 'Cebuano' },
  { code: 'co', name: 'Corsican' },
  { code: 'cs', name: 'Czech' },
  { code: 'cy', name: 'Welsh' },
  { code: 'da', name: 'Danish' },
  { code: 'de', name: 'German' },
  { code: 'el', name: 'Greek' },
  { code: 'en', name: 'English' },
  { code: 'eo', name: 'Esperanto' },
  { code: 'es', name: 'Spanish' },
  { code: 'et', name: 'Estonian' },
  { code: 'eu', name: 'Basque' },
  { code: 'fa', name: 'Persian' },
  { code: 'fi', name: 'Finnish' },
  { code: 'fr', name: 'French' },
  { code: 'fy', name: 'Frisian' },
  { code: 'ga', name: 'Irish' },
  { code: 'gd', name: 'Scots Gaelic' },
  { code: 'gl', name: 'Galician' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'ha', name: 'Hausa' },
  { code: 'haw', name: 'Hawaiian' },
  { code: 'he', name: 'Hebrew' },
  { code: 'hi', name: 'Hindi' },
  { code: 'hmn', name: 'Hmong' },
  { code: 'hr', name: 'Croatian' },
  { code: 'ht', name: 'Haitian Creole' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'hy', name: 'Armenian' },
  { code: 'id', name: 'Indonesian' },
  { code: 'ig', name: 'Igbo' },
  { code: 'is', name: 'Icelandic' },
  { code: 'it', name: 'Italian' },
  { code: 'iw', name: 'Hebrew' },
  { code: 'ja', name: 'Japanese' },
  { code: 'jw', name: 'Javanese' },
  { code: 'ka', name: 'Georgian' },
  { code: 'kk', name: 'Kazakh' },
  { code: 'km', name: 'Khmer' },
  { code: 'kn', name: 'Kannada' },
  { code: 'ko', name: 'Korean' },
  { code: 'ku', name: 'Kurdish' },
  { code: 'ky', name: 'Kyrgyz' },
  { code: 'la', name: 'Latin' },
  { code: 'lb', name: 'Luxembourgish' },
  { code: 'lo', name: 'Lao' },
  { code: 'lt', name: 'Lithuanian' },
  { code: 'lv', name: 'Latvian' },
  { code: 'mg', name: 'Malagasy' },
  { code: 'mi', name: 'Maori' },
  { code: 'mk', name: 'Macedonian' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'mn', name: 'Mongolian' },
  { code: 'mr', name: 'Marathi' },
  { code: 'ms', name: 'Malay' },
  { code: 'mt', name: 'Maltese' },
  { code: 'my', name: 'Myanmar (Burmese)' },
  { code: 'ne', name: 'Nepali' },
  { code: 'nl', name: 'Dutch' },
  { code: 'no', name: 'Norwegian' },
  { code: 'ny', name: 'Nyanja (Chichewa)' },
  { code: 'or', name: 'Odia (Oriya)' },
  { code: 'pa', name: 'Punjabi' },
  { code: 'pl', name: 'Polish' },
  { code: 'ps', name: 'Pashto' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ro', name: 'Romanian' },
  { code: 'ru', name: 'Russian' },
  { code: 'rw', name: 'Kinyarwanda' },
  { code: 'si', name: 'Sinhala' },
  { code: 'sk', name: 'Slovak' },
  { code: 'sl', name: 'Slovenian' },
  { code: 'sm', name: 'Samoan' },
  { code: 'sn', name: 'Shona' },
  { code: 'so', name: 'Somali' },
  { code: 'sq', name: 'Albanian' },
  { code: 'sr', name: 'Serbian' },
  { code: 'st', name: 'Sesotho' },
  { code: 'su', name: 'Sundanese' },
  { code: 'sv', name: 'Swedish' },
  { code: 'sw', name: 'Swahili' },
  { code: 'ta', name: 'Tamil' },
  { code: 'te', name: 'Telugu' },
  { code: 'tg', name: 'Tajik' },
  { code: 'th', name: 'Thai' },
  { code: 'tk', name: 'Turkmen' },
  { code: 'tl', name: 'Tagalog (Filipino)' },
  { code: 'tr', name: 'Turkish' },
  { code: 'tt', name: 'Tatar' },
  { code: 'ug', name: 'Uyghur' },
  { code: 'uk', name: 'Ukrainian' },
  { code: 'ur', name: 'Urdu' },
  { code: 'uz', name: 'Uzbek' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'xh', name: 'Xhosa' },
  { code: 'yi', name: 'Yiddish' },
  { code: 'yo', name: 'Yoruba' },
  { code: 'zh', name: 'Chinese' },
  { code: 'zu', name: 'Zulu' },
] as const

// Map browser language codes to our supported languages
export const LANGUAGE_MAP: Record<string, string> = {
  'af-ZA': 'af',
  'am-ET': 'am',
  'ar-SA': 'ar',
  'az-AZ': 'az',
  'be-BY': 'be',
  'bg-BG': 'bg',
  'bn-BD': 'bn',
  'bs-BA': 'bs',
  'ca-ES': 'ca',
  'ceb-PH': 'ceb',
  'co-FR': 'co',
  'cs-CZ': 'cs',
  'cy-GB': 'cy',
  'da-DK': 'da',
  'de-DE': 'de',
  'el-GR': 'el',
  'en-US': 'en',
  'en-GB': 'en',
  'eo': 'eo',
  'es-ES': 'es',
  'es-MX': 'es',
  'et-EE': 'et',
  'eu-ES': 'eu',
  'fa-IR': 'fa',
  'fi-FI': 'fi',
  'fr-FR': 'fr',
  'fr-CA': 'fr',
  'fy-NL': 'fy',
  'ga-IE': 'ga',
  'gd-GB': 'gd',
  'gl-ES': 'gl',
  'gu-IN': 'gu',
  'ha-NG': 'ha',
  'haw-US': 'haw',
  'he-IL': 'he',
  'hi-IN': 'hi',
  'hmn': 'hmn',
  'hr-HR': 'hr',
  'ht-HT': 'ht',
  'hu-HU': 'hu',
  'hy-AM': 'hy',
  'id-ID': 'id',
  'ig-NG': 'ig',
  'is-IS': 'is',
  'it-IT': 'it',
  'iw-IL': 'iw',
  'ja-JP': 'ja',
  'jw-ID': 'jw',
  'ka-GE': 'ka',
  'kk-KZ': 'kk',
  'km-KH': 'km',
  'kn-IN': 'kn',
  'ko-KR': 'ko',
  'ku-TR': 'ku',
  'ky-KG': 'ky',
  'la': 'la',
  'lb-LU': 'lb',
  'lo-LA': 'lo',
  'lt-LT': 'lt',
  'lv-LV': 'lv',
  'mg-MG': 'mg',
  'mi-NZ': 'mi',
  'mk-MK': 'mk',
  'ml-IN': 'ml',
  'mn-MN': 'mn',
  'mr-IN': 'mr',
  'ms-MY': 'ms',
  'mt-MT': 'mt',
  'my-MM': 'my',
  'ne-NP': 'ne',
  'nl-NL': 'nl',
  'no-NO': 'no',
  'ny-MW': 'ny',
  'or-IN': 'or',
  'pa-IN': 'pa',
  'pl-PL': 'pl',
  'ps-AF': 'ps',
  'pt-BR': 'pt',
  'pt-PT': 'pt',
  'ro-RO': 'ro',
  'ru-RU': 'ru',
  'rw-RW': 'rw',
  'si-LK': 'si',
  'sk-SK': 'sk',
  'sl-SI': 'sl',
  'sm-WS': 'sm',
  'sn-ZW': 'sn',
  'so-SO': 'so',
  'sq-AL': 'sq',
  'sr-RS': 'sr',
  'st-LS': 'st',
  'su-ID': 'su',
  'sv-SE': 'sv',
  'sw-TZ': 'sw',
  'ta-IN': 'ta',
  'te-IN': 'te',
  'tg-TJ': 'tg',
  'th-TH': 'th',
  'tk-TM': 'tk',
  'tl-PH': 'tl',
  'tr-TR': 'tr',
  'tt-RU': 'tt',
  'ug-CN': 'ug',
  'uk-UA': 'uk',
  'ur-PK': 'ur',
  'uz-UZ': 'uz',
  'vi-VN': 'vi',
  'xh-ZA': 'xh',
  'yi': 'yi',
  'yo-NG': 'yo',
  'zh-CN': 'zh',
  'zh-TW': 'zh',
  'zu-ZA': 'zu',
}

// Map language codes to Google Books API search terms
export const LANGUAGE_SEARCH_TERMS: Record<string, string> = {
  'af': 'language:af',
  'am': 'language:am',
  'ar': 'language:ar',
  'az': 'language:az',
  'be': 'language:be',
  'bg': 'language:bg',
  'bn': 'language:bn',
  'bs': 'language:bs',
  'ca': 'language:ca',
  'ceb': 'language:ceb',
  'co': 'language:co',
  'cs': 'language:cs',
  'cy': 'language:cy',
  'da': 'language:da',
  'de': 'language:de',
  'el': 'language:el',
  'en': 'language:en',
  'eo': 'language:eo',
  'es': 'language:es',
  'et': 'language:et',
  'eu': 'language:eu',
  'fa': 'language:fa',
  'fi': 'language:fi',
  'fr': 'language:fr',
  'fy': 'language:fy',
  'ga': 'language:ga',
  'gd': 'language:gd',
  'gl': 'language:gl',
  'gu': 'language:gu',
  'ha': 'language:ha',
  'haw': 'language:haw',
  'he': 'language:he',
  'hi': 'language:hi',
  'hmn': 'language:hmn',
  'hr': 'language:hr',
  'ht': 'language:ht',
  'hu': 'language:hu',
  'hy': 'language:hy',
  'id': 'language:id',
  'ig': 'language:ig',
  'is': 'language:is',
  'it': 'language:it',
  'iw': 'language:iw',
  'ja': 'language:ja',
  'jw': 'language:jw',
  'ka': 'language:ka',
  'kk': 'language:kk',
  'km': 'language:km',
  'kn': 'language:kn',
  'ko': 'language:ko',
  'ku': 'language:ku',
  'ky': 'language:ky',
  'la': 'language:la',
  'lb': 'language:lb',
  'lo': 'language:lo',
  'lt': 'language:lt',
  'lv': 'language:lv',
  'mg': 'language:mg',
  'mi': 'language:mi',
  'mk': 'language:mk',
  'ml': 'language:ml',
  'mn': 'language:mn',
  'mr': 'language:mr',
  'ms': 'language:ms',
  'mt': 'language:mt',
  'my': 'language:my',
  'ne': 'language:ne',
  'nl': 'language:nl',
  'no': 'language:no',
  'ny': 'language:ny',
  'or': 'language:or',
  'pa': 'language:pa',
  'pl': 'language:pl',
  'ps': 'language:ps',
  'pt': 'language:pt',
  'ro': 'language:ro',
  'ru': 'language:ru',
  'rw': 'language:rw',
  'si': 'language:si',
  'sk': 'language:sk',
  'sl': 'language:sl',
  'sm': 'language:sm',
  'sn': 'language:sn',
  'so': 'language:so',
  'sq': 'language:sq',
  'sr': 'language:sr',
  'st': 'language:st',
  'su': 'language:su',
  'sv': 'language:sv',
  'sw': 'language:sw',
  'ta': 'language:ta',
  'te': 'language:te',
  'tg': 'language:tg',
  'th': 'language:th',
  'tk': 'language:tk',
  'tl': 'language:tl',
  'tr': 'language:tr',
  'tt': 'language:tt',
  'ug': 'language:ug',
  'uk': 'language:uk',
  'ur': 'language:ur',
  'uz': 'language:uz',
  'vi': 'language:vi',
  'xh': 'language:xh',
  'yi': 'language:yi',
  'yo': 'language:yo',
  'zh': 'language:zh',
  'zu': 'language:zu',
}

// Helper function to get browser language
export function getBrowserLanguage(): string {
  if (typeof window === 'undefined') return 'en'
  
  // Get browser language
  const browserLang = navigator.language || (navigator as any).userLanguage
  if (!browserLang) return 'en'

  // Try to match the full language code
  const matchedLang = LANGUAGE_MAP[browserLang]
  if (matchedLang) return matchedLang

  // Try to match just the primary language code
  const primaryLang = browserLang.split('-')[0]
  const supportedLang = LANGUAGES.find(lang => lang.code === primaryLang)
  return supportedLang ? supportedLang.code : 'en'
} 